"""Pydantic schemas package."""

from app.schemas.health import HealthResponse, DatabaseHealth
from app.schemas.auth import (
    RoleEnum,
    UserRegisterRequest,
    UserLoginRequest,
    UserResponse,
    TokenResponse,
)
from app.schemas.patient import (
    PatientBase,
    PatientCreate,
    PatientUpdate,
    PatientResponse,
    PatientListResponse,
)
from app.schemas.disease import (
    ContagionTypeEnum,
    DiseaseBase,
    DiseaseCreate,
    DiseaseUpdate,
    DiseaseResponse,
    DiseaseListResponse,
)
from app.schemas.case import (
    CaseStatusEnum,
    SeverityEnum,
    DiseaseCaseBase,
    DiseaseCaseCreate,
    DiseaseCaseUpdate,
    DiseaseCaseResponse,
    DiseaseCaseListResponse,
)
from app.schemas.gis import (
    GeoJSONGeometry,
    GeoJSONFeature,
    GeoJSONFeatureCollection,
    DistrictGISResponse,
    LocalBodyGISResponse,
    WardGISResponse,
    CaseLocationPoint,
)
from app.schemas.consent import (
    ConsentStatusEnum,
    SessionStatusEnum,
    ConsentGrantRequest,
    ConsentRevokeRequest,
    ConsentResponse,
    SessionStartRequest,
    SessionStopRequest,
    SessionResponse,
    LocationObservationSubmit,
    LocationObservationResponse,
    PatientMonitoringStatusResponse,
    AuditLogResponse,
)

from app.schemas.prediction import (
    RiskLevelEnum,
    PredictedTrendEnum,
    OutbreakPredictionInput,
    AreaOutbreakPrediction,
    OutbreakPredictionResponse,
)

__all__ = [
    "HealthResponse",
    "DatabaseHealth",
    "RoleEnum",
    "UserRegisterRequest",
    "UserLoginRequest",
    "UserResponse",
    "TokenResponse",
    "PatientBase",
    "PatientCreate",
    "PatientUpdate",
    "PatientResponse",
    "PatientListResponse",
    "ContagionTypeEnum",
    "DiseaseBase",
    "DiseaseCreate",
    "DiseaseUpdate",
    "DiseaseResponse",
    "DiseaseListResponse",
    "CaseStatusEnum",
    "SeverityEnum",
    "DiseaseCaseBase",
    "DiseaseCaseCreate",
    "DiseaseCaseUpdate",
    "DiseaseCaseResponse",
    "DiseaseCaseListResponse",
    "GeoJSONGeometry",
    "GeoJSONFeature",
    "GeoJSONFeatureCollection",
    "DistrictGISResponse",
    "LocalBodyGISResponse",
    "WardGISResponse",
    "CaseLocationPoint",
    "ConsentStatusEnum",
    "SessionStatusEnum",
    "ConsentGrantRequest",
    "ConsentRevokeRequest",
    "ConsentResponse",
    "SessionStartRequest",
    "SessionStopRequest",
    "SessionResponse",
    "LocationObservationSubmit",
    "LocationObservationResponse",
    "PatientMonitoringStatusResponse",
    "AuditLogResponse",
]
